# Generated by Django 2.0 on 2018-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchallan', '0003_remove_fjob_slip_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fchallan',
            name='billed',
        ),
        migrations.AddField(
            model_name='fchallan',
            name='recieved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
