# Generated by Django 2.0 on 2018-01-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('fchallan', '0007_fchallan_single_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='fchallan',
            name='payment_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='fchallan',
            name='recieved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
