# Generated by Django 2.0 on 2018-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchallan', '0008_auto_20180131_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fjob',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fjob',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
