# Generated by Django 2.0 on 2018-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchallan', '0009_auto_20180403_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fchallan',
            name='challan_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
