# Generated by Django 2.0.1 on 2018-04-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchallan', '0010_auto_20180410_1929'),
        ('fchallan', '0009_auto_20180403_1619'),
    ]

    operations = [
    ]
