# Generated by Django 3.1.7 on 2021-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bill_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
