# Generated by Django 2.0 on 2018-01-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('remaining_payment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
        ),
    ]
