# Generated by Django 2.0 on 2018-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180519_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
