# Generated by Django 3.1.7 on 2021-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180519_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_bill_payment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
