# Generated by Django 2.0 on 2018-01-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('gross_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=3, max_digits=10)),
                ('other_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('recieved', models.DecimalField(decimal_places=3, max_digits=10)),
                ('deleted', models.BooleanField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
        ),
    ]
