# Generated by Django 2.0 on 2018-01-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
    ]
