# Generated by Django 2.0 on 2018-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_payment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
