# Generated by Django 2.0 on 2018-01-13 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pchallan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pchallan',
            name='job_date',
        ),
        migrations.AddField(
            model_name='pjob',
            name='job_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
