# Generated by Django 2.0 on 2018-01-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pchallan', '0002_auto_20180113_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pchallan',
            name='balance',
        ),
    ]
