# Generated by Django 2.0 on 2018-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pchallan', '0003_remove_pchallan_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjob',
            name='gst',
            field=models.DecimalField(decimal_places=3, default=100.01, max_digits=10),
            preserve_default=False,
        ),
    ]
