# Generated by Django 2.0 on 2018-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pchallan', '0004_pjob_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pchallan',
            name='slip_no',
        ),
        migrations.AddField(
            model_name='pjob',
            name='slip_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
