# Generated by Django 2.0 on 2018-01-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('pchallan', '0006_auto_20180127_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pchallan',
            name='recieved',
        ),
        migrations.AddField(
            model_name='pchallan',
            name='bill_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bill.bill'),
        ),
    ]
