# Generated by Django 2.0 on 2018-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pchallan', '0007_auto_20180127_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='pchallan',
            name='single_bill',
            field=models.BooleanField(default=False),
        ),
    ]
