# Generated by Django 2.0 on 2017-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_group',
            fields=[
                ('item_group_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('hsn_code', models.CharField(max_length=8)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
