# Generated by Django 2.0.6 on 2018-06-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='logs',
        ),
    ]
