# Generated by Django 2.0.6 on 2019-02-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_nickname'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slip',
            fields=[
                ('slip_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='slip_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('job_name', models.CharField(max_length=120)),
                ('quantity', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.items')),
                ('slip_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slips.slip')),
            ],
        ),
    ]
