# Generated by Django 2.0.6 on 2019-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='complted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slip_job',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
