# Generated by Django 2.0.6 on 2019-02-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0002_auto_20190223_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slip',
            old_name='complted',
            new_name='completed',
        ),
    ]
