# Generated by Django 2.0.6 on 2019-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0003_auto_20190223_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip_job',
            name='fb',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
