# Generated by Django 2.0.6 on 2019-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0004_slip_job_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='billed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
